### ISSUE TITLE
Component Epic- V1

### ISSUE THREAD

**Issue by twblack88** [makerdao/community-portal#2]
## Reference
[Components page](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413)
Ryan outlines some functionality here and also some UX of the final component. 

### Components list
See issues nested below in this epic. This list here is semi-prioritized, with links kept for canonical reference.  [**_Note_**]Checkmarks of tasks was just a reference from sprint_1 week_1 before we had epics from Zenhub.
 
- [x] [Page Heading](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#8714e287f8c94c2baf0afb5f37b3eb85) 
- [x] [Breadcrumbs](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#d085d7d6dfea4b4f86da13bab112d08a)
- [x] [Inline Code syntax](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#b3d09a0f2e21448297d5ef4ac61b98c4)
- [x] [Links](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#f2a62f15c0204e27b42286b9ac9fab83)
- [x] [Tabs](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A909) and [explainer](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#d6ddfe8ccace425bb63853494eac2fd6)
- [x] [CTA's aka buttons](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A288)
- [x] [Callout](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A1154)
- [x] [Status alert or banners](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A728)
- [x] [Touts](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A180)
- [x] [3 column chocolate box (learn content and Governance content are good examples)](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A1) and [explainer ](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#a1eeb7e0d62b4dd2ac52d6121779f3c0)
- [x] [Categories](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) and [explainer](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#d95ebf322bf84f82a474122bebadf758) 
- [x] [2- Column](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A1692)
- [x] [Process list](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A539)
- [x] [Lists](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=39%3A1)
- [x] [Checklists](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=294%3A126)
- [x] [Accordian](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=398%3A1477)
- [x] [Info blocks (image + copy)](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=294%3A295)
- [x] [Language Selector](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=385%3A0)
- [x] [Image](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=398%3A2608)
- [x] [Inline video](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A0) 
- [x] [Multi video](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A0)
- [x] [Alternative Header](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A632) and [explainer](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413#e479a9b64c304c36b2cfb50329243bf6) 
- [x] Inline GIF <-- not mocked up but in original feature list. Especially for active resources on front ends, or projects due to change, an easy swap out for GIFs that are updated might keep the copy evergreen and the visuals subject to updates. 

##### Nice to have
- [ ] [Vote card](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A2069)
- [ ] [Progressive disclosure (E.g., "show 10 more topics")](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=486%3A909)

Perhaps we can iframe in components from the mkrgov dash and transparency dash when appropriate (Subject to opening another issue and a discussion about if it's possible). 
- iFrame of mkrgov.science
- iFrame of transparency Dash

**Comment by MaximumCrash** [comment]
@twblack88 Inline Gif support is possible just by using the image component like you would normally. 

```
[Hello](https://urltogif.com/inline.gif)
```
